### ISSUE TITLE
U+2218 Ring operator (\circ) is very small

### ISSUE THREAD

**Issue by PhilippImhof** [Stone-Zeng/FiraMath#73]
Currently, the ring operator is very small. Size of operators has already been discussed in #39. See comparison between Fira Math (blue) and Latin Modern Math (red):

<img width="599" alt="image" src="https://user-images.githubusercontent.com/52650214/169652824-4c1e69b7-0976-4a7c-8f26-4e39440fdfb8.png">

One negative side effect is that expressions like `$30^\circ$` are barely readable:

<img width="474" alt="image" src="https://user-images.githubusercontent.com/52650214/169652888-93bec04a-bc8f-45e9-9701-6b57fd3b1f22.png">

There has been a discussion in #34 that one should not use `^\circ` for degrees, and while I agree that one should use the correct symbol (i.e. U+00B0 DEGREE SIGN), we know that `^\circ` has a long history and is widely used (I believe it was even used by siunitx in some versions).

I suggest making the circle operator a bit larger.

**Comment by stone-zeng** [comment]
I made this symbol too small because in [Unicode TR25](https://www.unicode.org/reports/tr25/tr25-15.pdf) it was categorized as "very small". But compared with other fonts, I think it's better to make it larger:

<img width="1012" alt="Screen Shot 2022-05-21 at 23 35 21" src="https://user-images.githubusercontent.com/18233088/169658759-d89c2c55-9f9e-4724-babb-4061202e3fc3.png">
